version: '3'
services:
  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver:8.1.0-stable
    user: "lms:lms"
    volumes:
      - /opt/lms/config:/config:rw
      - /opt/lms/music:/music:rw
      - /opt/lms/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9001:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    network_mode: "host"
    restart: always
