version: '3'
volumes:
  config:
    external: true
  music:
    external: true
  playlist:
    external: true  
services:
  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver:8.1.0-stable
    volumes:
      - config:/config:rw
      - music:/music:rw
      - playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9001:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    network_mode: "host"
    restart: always
